### ISSUE TITLE
Hard Sample mining

### ISSUE THREAD

**Issue by jlian2** [tjddus9597/Proxy-Anchor-CVPR2020#4]
Did you try hard sample mining in this loss?

**Comment by alexisdrakopoulos** [comment]
@jlian2 Proxy based losses can be thought of as group losses over an entire batch. I am not sure how mining would function/benefit group losses in this setting unless you are looking at some form of offline mining?

**Comment by sung-yeon-kim** [comment]
We have not applied hard sample mining to our loss. For proxy anchor loss, I think that there is no need for hard sampling since
1. Proxy anchor loss utilizes proxies, so its training complexity is already low compared to pair-based losses.
2. and, the weighting scheme is applied instead of sampling.
